.TH Frenzch.sh "1" "September 2022" "Frenzch.sh 0.3.1"
.SH NAME
Frenzch.sh \- A simple, cozy system info thingy
.SH Synopsis
.B frenzch.sh
.SH DESCRIPTION
Frenzch.sh, a simple system information tool that was
never meant to be used as a system information tool
and more as eyecandy to flex your setup. frenzch.sh
changes its fetch info according to the terminal size.
Go figure.
.SH OPTIONS
.TP
\fB\-\-version\fR
Print frenzch version
\fB\-\-args\fR
Put the stuff you want to see.
Example: --args os us wm ram
.IP
Example: frenzch.sh --config $HOME/Downloads/config
.SH "CONTRIBUTING"
Feel free to contribute, frenzch has a lot of room to improve!
Send a PR at https://github.com/FrenzyExists/frenzch.sh/pulls
.SH "REPORTING BUGS"
Report bugs to https://github.com/FrenzyExists/frenzch.sh/issues
