.TH Frenzch.sh "1" "September 2021" "Frenzch.sh 0.3.0"
.SH NAME
Frenzch.sh \- A simple, cozy system info thingy
.SH Synopsis
.B frenzch.sh
.SH DESCRIPTION
Frenzch.sh, a simple system information tool that was 
never meant to be used as a system information tool 
and more as eyecandy to flex your setup. Also, fuck 
logos. One more thing: frenzch.sh changes its fetch info
according to the terminal size, so, go figure.
.SH OPTIONS
.TP
\fB\-\-version\fR
Print frenzch version
.TP
\fB\-\-config\fR
specifies the location of your config file
.IP
Example: frenzch.sh --config $HOME/Downloads/config
.SH "CONTRIBUTING"
Frenzch.sh is still in a very e
.SH "REPORTING BUGS"
Report bugs to https://github.com/FrenzyExists/frenzch.sh/issues 
